name: Java CI mit Maven

on:
  push:
    - 'neue-fische/testing/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: neue-fische/testing

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Java einrichten
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Maven Build & Tests ausführen
        run: mvn -B package